/robot_state_publisher:
  ros__parameters:
    robot_description: $(command 'xacro $(var urdf_path)')

/create:
  ros__parameters:
    topic: robot_description

/rviz2:
  ros__parameters:
    -d: $(find-pkg-share my_robot_description)/rviz/my_robot_config.rviz